name: Build and deploy ASP.Net Core app to an Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: demo1005-web01    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/webapp01

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: './src/global.json'

      - name: Build with dotnet
        working-directory: './src/webapp01'
        run: |
            dotnet restore
            dotnet build 
            dotnet publish -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: webapp01
          path: './src/webapp01/publish'

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp01

      - name: Zip package
        run: |
          zip -r webapp01.zip ./*
          ls -la

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./webapp01.zip
