name: Build and deploy ASP.Net Core app to an Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: demo1005-web01    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: './publish'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/webapp01

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2

      - name: Build with dotnet
        run: |
          dotnet restore
          dotnet build 
          dotnet publish -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: webapp01
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp01

      - run: ls -la

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
